services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"

  keycloak:
    image: quay.io/keycloak/keycloak
    ports:
      - "8080:8080"

  backend:
    build: ./backend
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"

  nginx:
    image: nginx
    ports:
      - "80:80"
